### PR TITLE
Implement-the-Lock-Campaign-Function

### PR DESCRIPTION
**Pull request by ONEONUORA**

### CODE REVIEW

**Comment by mubarak23** [comment]
point this PR to develop

**Comment by mubarak23** [comment]
once this [PR](https://github.com/Token-Giver/token-giver-contracts/pull/50) is merged, closed this PR,  pull from the develop and follow through what he did

i.e 
`
ILockableDispatcher { contract_address: campaign_address }.locked(until)`

**Comment by ONEONUORA** [comment]
okay,

**Comment by ONEONUORA** [comment]
Closed

**Pull request closed without merging**
